name: VS Code Arduino Language Server

on:
  push:
    branches:
      - master
  workflow_dispatch:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 2 * * *' # run every day at 2AM

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Build VS Code Extension
        run: |
            yarn

      - name: Upload VS Code Extension [GitHub Actions]
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: electron/build/dist/build-artifacts/

      - name: Upload VS Code Extension [S3]
        if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && github.ref == 'refs/heads/master')
        uses: docker://plugins/s3
        env:
          PLUGIN_SOURCE: "build-artifacts/*"
          PLUGIN_STRIP_PREFIX: "build-artifacts/"
          PLUGIN_TARGET: "/vscode-arduino-language-server/nightly"
          PLUGIN_BUCKET: ${{ secrets.DOWNLOADS_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
